name: React build
on:
  push: # main Branch에서 push 이벤트가 일어났을 때만 실행
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # 레포지토리 체크아웃
        uses: actions/checkout@main

      - name: Cache node modules # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: admin/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
        
      - name: .env Setting # 환경변수 설정
        env:
          REACT_APP_COMPONENT_API_KEY: ${{ secrets.REACT_APP_COMPONENT_API_KEY }}
        run: |
          cd admin
          echo "REACT_APP_COMPONENT_API_KEY=$REACT_APP_COMPONENT_API_KEY" >> .env
          cat .env

      - name: Install Dependencies # 의존 파일 설치
        run: |
          cd admin
          npm install

      - name: Build # React Build
        run: |
          cd admin
          CI='' npm run build

      - name: Deploy # S3에 배포하기
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            admin/build s3://vikrant.store
